# Base Image
FROM python:3.9

# working directory
WORKDIR /app

# copy requirements file
COPY requirements.txt .

# run pip install and install dependencies
RUN pip install --no-cache-dir -r requirements.txt


# copy the rest of project files
COPY . .

# expose port
EXPOSE 5000

# command to run the application
CMD ["python", "app.py"]